{% set name = "pesummary" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4cdebc2a306d76e9c035205c146bfb161ebdbc14a4e458ad9f6c852043d5af5b

build:
  entry_points:
    - summaryclassification = pesummary.cli.summaryclassification:main
    - summaryclean = pesummary.cli.summaryclean:main
    - summarycombine = pesummary.cli.summarycombine:main
    - summarycompare = pesummary.cli.summarycompare:main
    - summarydetchar = pesummary.cli.summarydetchar:main
    - summarygracedb = pesummary.cli.summarygracedb:main
    - summaryjscompare = pesummary.cli.summaryjscompare:main
    - summarymodify = pesummary.cli.summarymodify:main
    - summarypages = pesummary.cli.summarypages:main
    - summarypageslw = pesummary.cli.summarypageslw:main
    - summarypipe = pesummary.cli.summarypipe:main
    - summaryplots = pesummary.cli.summaryplots:main
    - summarypublication = pesummary.cli.summarypublication:main
    - summaryrecreate = pesummary.cli.summaryrecreate:main
    - summaryreview = pesummary.cli.summaryreview:main
    - summarytest = pesummary.cli.summarytest:main
    - summaryversion = pesummary.cli.summaryversion:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - astropy >=3.2.3
    - corner
    - deepdish
    - gwpy
    - h5py
    - ligo.skymap
    - matplotlib-base
    - numpy >=1.15.4
    - p_astro
    - pandas
    - pepredicates >=0.0.2
    - plotly
    - pygments
    - pytables
    - python
    - ligo-gracedb
    - python-lal
    - python-lalsimulation >=2.0.0
    - python-lalinference
    - scipy
    - seaborn
    - statsmodels
    - tqdm >=4.44.0

test:
  imports:
    - pesummary
  commands:
    - summarytest --type imports
    - summarytest --type executables

about:
  home: https://git.ligo.org/lscsoft/pesummary
  doc_url: https://lscsoft.docs.ligo.org/pesummary/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to produce summary pages for Parameter estimation codes
  description: |
    This package helps the user to generate summary webpages to
    visualise the output from any parameter estimation code

extra:
  recipe-maintainers:
    - duncanmmacleod
    - hoyc1
