{% set name = "pesummary" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9450a3d0f60de067610e8033a6639391d46ef31fd5d0fd5738da10ebf4335987
  patches:
    - clean-requirements.patch

build:
  entry_points:
    - summaryclassification = pesummary.cli.summaryclassification:main
    - summaryclean = pesummary.cli.summaryclean:main
    - summarycombine = pesummary.cli.summarycombine:main
    - summarycombine_posteriors = pesummary.cli.summarycombine_posteriors:main
    - summarycompare = pesummary.cli.summarycompare:main
    - summarydetchar = pesummary.cli.summarydetchar:main
    - summaryextract = pesummary.cli.summaryextract:main
    - summarygracedb = pesummary.cli.summarygracedb:main
    - summaryjscompare = pesummary.cli.summaryjscompare:main
    - summarymodify = pesummary.cli.summarymodify:main
    - summarypages = pesummary.cli.summarypages:main
    - summarypageslw = pesummary.cli.summarypageslw:main
    - summarypipe = pesummary.cli.summarypipe:main
    - summaryplots = pesummary.cli.summaryplots:main
    - summarypublication = pesummary.cli.summarypublication:main
    - summaryrecreate = pesummary.cli.summaryrecreate:main
    - summaryreview = pesummary.cli.summaryreview:main
    - summarysplit = pesummary.cli.summarysplit:main
    - summarytest = pesummary.cli.summarytest:main
    - summarytgr = pesummary.cli.summarytgr:main
    - summaryversion = pesummary.cli.summaryversion:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools_scm
  run:
    - astropy >=4.0
    - corner
    - deepdish
    - gwpy >=2.1.2
    - h5py
    - ligo-gracedb
    - ligo.em-bright >=1.1.5
    - matplotlib-base <3.8.0
    - numpy >=1.15.4
    - pandas
    - plotly
    - pygments
    - pytables
    - python >=3.9
    - python-lal
    - python-lalsimulation >=5.0.0
    - python-lalinference
    - scipy >=1.8.0
    - seaborn >=0.12.2,<0.13.0
    - statsmodels
    - tqdm >=4.44.0
  run_constrained:
    - bilby >=1.1.1

test:
  requires:
    - pip
    - nbformat
  commands:
    # check requirements
    - python -m pip check pesummary
    - python -m pip show pesummary
    # run basic sanity checks
    - summarytest --type imports
    - summarytest --type executables

about:
  home: https://git.ligo.org/lscsoft/pesummary
  doc_url: https://lscsoft.docs.ligo.org/pesummary/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to produce summary pages for Parameter estimation codes
  description: |
    This package helps the user to generate summary webpages to
    visualise the output from any parameter estimation code

extra:
  recipe-maintainers:
    - duncanmmacleod
    - hoyc1
