{% set name = "pesummary" %}
{% set version = "0.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f881fe84c0ffe13bcbefd985a73370128070b953ed8db6abd2b75752836709c6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy
    - corner
    - deepdish
    - h5py
    - lscsoft-glue
    - matplotlib-base
    - numpy
    - pandas
    - pygments
    - python >=3.6
    - python-lal
    - python-lalsimulation
    - scipy

test:
  imports:
    - pesummary
    - pesummary.gw
    - pesummary.gw.file
    - pesummary.gw.plot
    - pesummary.core
    - pesummary.core.css
    - pesummary.core.js
    - pesummary.core.file
    - pesummary.core.plot
    - pesummary.utils
    - pesummary.core.webpage
  commands:
    - summarypages --help

about:
  home: https://git.ligo.org/charlie.hoy/pesummary
  doc_url: https://docs.ligo.org/charlie.hoy/pesummary/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to produce summary pages for Parameter estimation codes
  description: |
    This package helps the user to generate summary webpages to
    visualise the output from both LALInference and Bilby.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - hoyc1
