{% set name = "pesummary" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c4e8bbdb1db71dc32fb2e13c016e7fd1f152a553b9a0fadb05d424227705f24

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy
    - corner
    - deepdish
    - h5py
    - lscsoft-glue
    - matplotlib-base
    - numpy
    - pandas
    - pygments
    - python >=3.6
    - python-lal
    - python-lalsimulation
    - scipy

test:
  imports:
    - pesummary
    - pesummary.css
    - pesummary.js
    - pesummary.one_format
    - pesummary.plot
    - pesummary.utils
    - pesummary.webpage
  commands:
    - summarypages.py --help

about:
  home: https://git.ligo.org/charlie.hoy/pesummary
  doc_url: https://docs.ligo.org/charlie.hoy/pesummary/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to produce summary pages for Parameter estimation codes
  description: |
    This package helps the user to generate summary webpages to
    visualise the output from both LALInference and Bilby.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - hoyc1
