{% set name = "pesummary" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1ba9dfd212e45f90cadefbf95a4d3d8a9cbf3481d08328cc6a14b785e5f0bc9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - summaryconvert = pesummary.gw.file.one_format:main
    - summarypages = pesummary.cli.summarypages:main
    - summaryplots = pesummary.cli.summaryplots:main
    - summarypublication = pesummary.cli.summarypublication:main
    - summaryclassification = pesummary.cli.summaryclassification:main
    - summaryclean = pesummary.cli.summaryclean:main
    - summaryreview = pesummary.cli.summaryreview:main
    - summarycombine = pesummary.cli.summarycombine:main
    - summarycombine_metafiles = pesummary.cli.summarycombine_metafiles:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy
    - corner
    - deepdish
    - gwpy
    - h5py
    - lscsoft-glue
    - matplotlib-base
    - numpy
    - pandas
    - pygments
    - python >=3.6
    - python-lal
    - python-lalsimulation
    - scipy
    - seaborn
    - statsmodels
    - pepredicates
    - plotly

test:
  imports:
    - pesummary
    - pesummary.conf
    - pesummary.core.css
    - pesummary.core.file
    - pesummary.core.file.formats
    - pesummary.core.js
    - pesummary.core.file
    - pesummary.core.plots
    - pesummary.core.webpage
    - pesummary.gw
    - pesummary.gw.file
    - pesummary.gw.file.formats
    - pesummary.gw.pepredicates
    - pesummary.gw.plots
    - pesummary.utils
  commands:
    - summarypages --help
    - summaryplots --help
    - summarypublication --help
    - summaryclassification --help
    - summaryclean --help
    - summaryreview --help
    - summarycombine --help
    - summarycombine_metafiles --help
    - summaryversion --help
    - summarydetchar --help

about:
  home: https://git.ligo.org/lscsoft/pesummary
  doc_url: https://lscsoft.docs.ligo.org/pesummary/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to produce summary pages for Parameter estimation codes
  description: |
    This package helps the user to generate summary webpages to
    visualise the output from any parameter estimation code

extra:
  recipe-maintainers:
    - duncanmmacleod
    - hoyc1
