{% set name = "pesummary" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72c211dada1ddbad3f92fb1db9bfa128a395e15f3d8e6841d08adb431f39c1aa

build:
  entry_points:
    - summaryclassification = pesummary.cli.summaryclassification:main
    - summaryclean = pesummary.cli.summaryclean:main
    - summarycombine = pesummary.cli.summarycombine:main
    - summarydetchar = pesummary.cli.summarydetchar:main
    - summarymodify = pesummary.cli.summarymodify:main
    - summarypages = pesummary.cli.summarypages:main
    - summarypageslw = pesummary.cli.summarypageslw:main
    - summarypipe = pesummary.cli.summarypipe:main
    - summaryplots = pesummary.cli.summaryplots:main
    - summarypublication = pesummary.cli.summarypublication:main
    - summaryrecreate = pesummary.cli.summaryrecreate:main
    - summaryreview = pesummary.cli.summaryreview:main
    - summaryversion = pesummary.cli.summaryversion:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy >=3.2.3
    - corner
    - deepdish
    - gwpy
    - h5py
    - ligo.skymap
    - matplotlib-base
    - numpy >=1.15.4
    - p_astro
    - pandas <1.0.0a0
    - pepredicates >=0.0.2
    - plotly
    - pygments
    - pytables
    - python >=3.6
    - python-lal
    - python-lalsimulation >=2.0.0
    - python-lalinference
    - scipy
    - seaborn
    - statsmodels

test:
  imports:
    - pesummary
    - pesummary.conf
    - pesummary.core.css
    - pesummary.core.file
    - pesummary.core.file.formats
    - pesummary.core.js
    - pesummary.core.file
    - pesummary.core.plots
    - pesummary.core.webpage
    - pesummary.gw
    - pesummary.gw.file
    - pesummary.gw.file.formats
    - pesummary.gw.pepredicates
    - pesummary.gw.p_astro
    - pesummary.gw.plots
    - pesummary.gw.plots.bounded_2d_kde
    - pesummary.gw.plots.detchar
    - pesummary.gw.plots.main
    - pesummary.gw.plots.violin
    - pesummary.io
    - pesummary.utils
  commands:
    - summaryclassification --help
    - summaryclean --help
    - summarycombine --help
    - summarydetchar --help
    - summarymodify --help
    - summarypages --help
    - summarypageslw --help
    - summarypipe --help
    - summaryplots --help
    - summarypublication --help
    - summaryrecreate --help
    - summaryreview --help
    - summaryversion --help

about:
  home: https://git.ligo.org/lscsoft/pesummary
  doc_url: https://lscsoft.docs.ligo.org/pesummary/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to produce summary pages for Parameter estimation codes
  description: |
    This package helps the user to generate summary webpages to
    visualise the output from any parameter estimation code

extra:
  recipe-maintainers:
    - duncanmmacleod
    - hoyc1
