travis:
  secure:
    BINSTAR_TOKEN: jh18qSid9ctnPDXqsT54UHvOLP/Ok05TpUG6EUqVu2V2t9/7a7yeRYG9vaH7avQY5euc//Yj24rGJC81g/bMVb9VGDEFr3vQhnaPB6+tfWfGqV0m0lVUblqUjTsxVwu1AHI1SRp3tJtkyXDUkuY0G4dd0bRLeYbAdAS1kweFzHcT0U6shiYqnfbQVAI5+CEHMEQ6R6CsG4NVL55oZWJ/PAzWDlxifld4m6pKwyymcSuJORSLW0WFv03ik1oTiYe21rVqFzQw9vavYvVHaTj5XKFB4LUqamBHTX0yrw6bt1tgc4Mu5xbQ1Ia+k7r2PuIUiUO6cJ0EU8DYfYxkv6NoF3XH3u6z07aRZNudMl0fifGXRKcWiY0w1MVFCp9+RNgmGuKxoSjsY2ZvUE91h+E0+y8f24Ns+fXTGUTume346XMj+2tSauP1VoSBBDz/nQfOsgMwDnpy5Ei243t1fHL80MWE74oeiPN6+YMDJl3m9JEP9prPX2npyoAfsOWoFWc3mx4HJuTlvJMC6xBumkyqnWIjSSkjy2XfoQhdm1GHwpBHfLIWygug17QewWC99HuWS5fZrG2SgX2QOF0hXMP9vfKKp0bDuYgfrLp5VirLUeu+nV3vJGG+t8bUBjiFxabZlHRs7uGkvFgtonhk6L7g3fRj88bnHmh+Yqi4Xbdkx4U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
